
module.exports = {
    products: [
        {
            _id: '1',
            name: 'Long Sleeve Dry Fit',
            category: 'Shirts',
            image: '/images/product-1.jpg',
            price: 34,
            brand: 'All-in Wear',
            rating: 4.6,
            numReviews: 12,
            countInStock: 5,
        },
        {
            _id: '2',
            name: 'Dry Fit Hoodie',
            category: 'Hoodie',
            image: '/images/product-2.jpg',
            price: 40,
            brand: 'NuFit Apparel',
            rating: 5,
            numReviews: 9,
            countInStock: 25,
        },
        {
            _id: '3',
            name: 'Gym Zip-Up Hoodie',
            category: 'Hoodie',
            image: '/images/product-3.jpg',
            price: 45,
            brand: 'FitNation',
            rating: 4.8,
            numReviews: 15,
            countInStock: 7,
        },
        {
            _id: '4',
            name: 'Running Pants',
            category: 'Pants',
            image: '/images/product-4.jpg',
            price: 28,
            brand: 'Level Up Co.',
            rating: 3.5,
            numReviews: 17,
            countInStock: 8,
        },
        {
            _id: '5',
            name: 'Compression Gym Shirt',
            category: 'Shirts',
            image: '/images/product-5.jpg',
            price: 35,
            brand: 'Level Up Co.',
            rating: 4.6,
            numReviews: 12,
            countInStock: 5,
        },
        {
            _id: '6',
            name: 'Running Shorts',
            category: 'Shorts',
            image: '/images/product-6.jpg',
            price: 19,
            brand: 'Level Up Co.',
            rating: 3.8,
            numReviews: 15,
            countInStock: 32,
        },
    ],
};